spring.application.name=SpringBootGenAi

#spring.ai.google.genai.api-key=your_key
#spring.ai.google.genai.chat.options.model=gemini-1.5-flash-latest

spring.ai.model.chat=ollama
spring.ai.ollama.chat.model=llama3.2:1b
