spring.application.name=SpringBootOpenAi
openai.api.key=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

server.port=9091

spring.ai.openai.api-key==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




